#!/usr/bin/env python3
"""Embed luced/grammars/*.tmLanguage.json into a Luce module that seeds them into the config
directory on first run, so highlighting works out of the box. Re-run after changing a grammar."""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
GRAMMARS = ROOT / "grammars"
OUT = ROOT / "src/language/default_grammars.luc"


def escape(text):
    out = []
    for ch in text:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == "\"":
            out.append("\\\"")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif code < 32:
            out.append("\\u{%x}" % code)
        else:
            out.append(ch)
    return "".join(out)


def main():
    files = sorted(GRAMMARS.glob("*.tmLanguage.json"))
    lines = [
        "## Generated by tools/grammars.py — do not edit. The grammars shipped with luced,",
        "## written into the config directory on first run so highlighting works out of the box.",
        "import files",
        "import workspace.paths as paths",
        "",
        "func write_default(directory: str, name: str, content: str) -> unit!:",
        "    files.create_text(paths.join(directory, name), content) catch failure:",
        "        if failure.code != files.already_exists:",
        "            error(failure.code, failure.message)",
        "",
        "## Write each bundled grammar into `directory`, keeping any file the user already has.",
        "pub func seed(directory: str) -> unit!:",
    ]
    for path in files:
        lines.append("    try write_default(directory, \"%s\", \"%s\")" % (path.name, escape(path.read_text())))
    if not files:
        lines.append("    return")
    OUT.write_text("\n".join(lines) + "\n")
    print("wrote %s (%d grammars)" % (OUT, len(files)))


if __name__ == "__main__":
    main()
